# Generated by Django 5.2.7 on 2025-10-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reservation_restaurantanalytics_restaurantowner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Usuário Comum'), ('restaurant_owner', 'Proprietário de Restaurante')], default='user', max_length=20),
        ),
    ]
